#! /bin/sh
#                             _ _       
#  /\/\  _ __ /\/\   __ _  __| (_)_   __
# /    \| '__/    \ / _` |/ _` | \ \ / /
#/ /\/\ \ | / /\/\ \ (_| | (_| | |\ V / 
#\/    \/_| \/    \/\__,_|\__,_|_| \_/  
#                                       
# Autostartup Apps
/home/senithu/.config/bspwm/autostart.sh

# Config
bspc monitor HDMI-1 -d 1 2 3 4 5
bspc monitor eDP-1 -d 1
bspc config border_width 2
bspc config focused_border_color "#7aa2f7"
bspc config normal_border_color "#11121d"
bspc config window_gap 8
bspc config split_ratio 0.52
bspc config single_monocle false
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true
bspc config pointer_motion_interval 0.6

# Rules

bspc rule -a Screenkey manage=off
bspc rule -a zoom state=floating
bspc rule -a SimpleScreenRecorder state=floating
bspc rule -a scpad sticky=on state=floating rectangle=1000x600+480+180
bspc rule -a albert:albert border=off
